server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Xử lý React Router (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy các request API tới backend thật (VD: Render)
    location /api/ {
        proxy_pass https://e-commerce-project-0hsd.onrender.com/api/;
        proxy_ssl_server_name on; # Bắt buộc khi gọi tới HTTPS bên ngoài
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
